version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: employee_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employeeprojectdb
      MYSQL_USER: avk
      MYSQL_PASSWORD: avkpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
